### ISSUE TITLE
重新整理的ERROR

### ISSUE THREAD

**Issue by zombie5454** [hermes926/Redanews#49]
如果在登入後進入遊戲，然後按重新整理，雖然你的帳號沒被登出，但你之前的guess不會載入到guessTable，如果這時候你submit之前出現過的guess，你下次登入就會有一些可怕的事，以下是我用帳密star / hermes1111發生的，可以看到hello出現好幾次。
![螢幕擷取畫面 2023-01-02 022229](https://user-images.githubusercontent.com/56215459/210181077-b4105c9c-cc42-437b-95db-3e859d791b6b.png)

**Comment by Chienyu-1215** [comment]
The problems seems to be fixed when I designed the new history modal (4a1bf7a71ab76253b0959a3bdef4cd3447974a26), PR will be made this afternoon and I'll close it then.
